version = 4
enable_cursor_positioning = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'blue'

[transient_prompt]
  template = '❯ '
  style = 'plain'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}blue{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'magenta'
    type = 'path'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} *{{ .StashCount }}{{ end }}'
    foreground = 'lightGreen'
    type = 'git'
    style = 'plain'
  
    [properties]
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    foreground = 'yellow'
    type = 'executiontime'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .CurrentDate | date .Format }}'
    foreground = 'cyan'
    type = 'time'
    style = 'plain'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯ '
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}blue{{end}}']
