export ZSH="$HOME/.oh-my-zsh"

# Set name of theme, "random" to set random (echo $RANDOM_THEME to view). 
ZSH_THEME=""

# Set list of themes to pick from when loading at random (if not empty)
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# zstyle ':omz:update' mode auto      # update automatically without asking

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Mass Global Updates
mgu() {
  brew update;
  brew upgrade;
  brew upgrade --cask;
  brew link --overwrite node;
  npm update -g;
  bun upgrade;
  omz update;
  # python -m pip install --upgrade pip;
}

# bun completions
[ -s "/Users/jordan/.bun/_bun" ] && source "/Users/jordan/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Set python
# export PATH="/opt/homebrew/opt/python@3.14/bin:$PATH"
# Give homebrew priority
export PATH="/opt/homebrew/bin:$PATH"

# Alias python3 to python
alias python="python3"
alias pip="pip3"

# Set nvim as the default editor
export EDITOR='nvim'

# Alias nvim to vim
alias vim="nvim"

# Change default manual pager from less to nvim
export MANPAGER='nvim +Man!'

# OhMyPosh
if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
    eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/theme.toml)"
fi

if type rg &> /dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files'
  export FZF_DEFAULT_OPTS='-m'
fi

# --cmd cd rewrites the 'z' command to 'cd'
eval "$(zoxide init --cmd cd zsh)"
alias zoxlist="zoxide query -l -s"
alias zlist="zoxide query -l -s"

# Hide homebrew env hint
HOMEBREW_NO_ENV_HINTS="true"

# Surpress npm warnings because im sick of seeing them
export npm_config_loglevel=silent

# Allows for proper config location (~/.config) of some terminal applications (ex aerc)
export XDG_CONFIG_HOME="$HOME/.config"

# "$HOME/.local/bin/env"
export PATH=$PATH:$HOME/go/bin

# Stop git from opening nvim every time I pull
export GIT_MERGE_AUTOEDIT=no

if command -v symfony &>/dev/null; then
  eval "$(symfony completion)"
fi

# Fix 'xterm-kitty' unknown terminal type in ssh
alias ssh='TERM=xterm-256color ssh'

# Herd injected PHP 8.4 configuration.
export HERD_PHP_84_INI_SCAN_DIR="/Users/jordan/Library/Application Support/Herd/config/php/84/"

# Herd injected PHP binary.
export PATH="/Users/jordan/Library/Application Support/Herd/bin/":$PATH

# Herd injected PHP 8.5 configuration.
export HERD_PHP_85_INI_SCAN_DIR="/Users/jordan/Library/Application Support/Herd/config/php/85/"

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba shell init' !!
export MAMBA_EXE='/opt/homebrew/opt/micromamba/bin/mamba';
export MAMBA_ROOT_PREFIX='/Users/jordan/mamba';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias mamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<

alias conda="mamba"


# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/jordan/Library/Application Support/Herd/config/php/83/"
