export ZSH="$HOME/.oh-my-zsh"

# Set name of theme, "random" to set random (echo $RANDOM_THEME to view). 
ZSH_THEME="zhann"

# Set list of themes to pick from when loading at random (if not empty)
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# zstyle ':omz:update' mode auto      # update automatically without asking

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

nvm() {
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    nvm "$@"
}

alias sweep="find . -name .DS_Store -type f -delete ; find -name .Trashes -type d -delete ; find . -type d | xargs dot_clean -m"

# bun completions
[ -s "/Users/jordan/.bun/_bun" ] && source "/Users/jordan/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Set python
export PATH="/Users/jordan/Library/Python/3.11/bin:$PATH"

# Set PHP to default path
export PATH="/path/to/homebrew/php/bin:$PATH"

# --cmd cd rewrites the 'z' command to 'cd'
eval "$(zoxide init --cmd cd zsh)"
alias zoxlist="zoxide query -l -s"
alias zlist="zoxide query -l -s"

# Hide homebrew env hint
HOMEBREW_NO_ENV_HINTS="true"

# Surpress npm warnings because im sick of seeing them
export npm_config_loglevel=silent

# Change default manual pager from less to nvim
export MANPAGER='nvim +Man!'

# Allows for proper config location (~/.config) of some terminal applications (ex aerc)
export XDG_CONFIG_HOME="$HOME/.config"

# . "$HOME/.local/bin/env"
export PATH=$PATH:$HOME/go/bin

# Set nvim as the default editor
export EDITOR='nvim'
