export ZSH="$HOME/.oh-my-zsh"

# Set name of theme, "random" to set random (echo $RANDOM_THEME to view). 
ZSH_THEME=""

# Set list of themes to pick from when loading at random (if not empty)
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# zstyle ':omz:update' mode auto      # update automatically without asking

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

nvm() {
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    nvm "$@"
}

alias sweep="find . -name .DS_Store -type f -delete ; find -name .Trashes -type d -delete ; find . -type d | xargs dot_clean -m"

# Mass Global Updates
mgu() {
  brew update;
  brew upgrade;
  brew upgrade --cask;
  brew link --overwrite node;
  npm update -g;
  omz update;
  bun upgrade;
  python -m pip install --upgrade pip;
}

# bun completions
[ -s "/Users/jordan/.bun/_bun" ] && source "/Users/jordan/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Set python
export PATH="/Users/jordan/Library/Python/3.11/bin:$PATH"

# Alias nvim to vim
alias vim="nvim"

# OhMyPosh
if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
    eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/theme.toml)"
fi

if type rg &> /dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files'
  export FZF_DEFAULT_OPTS='-m'
fi

# --cmd cd rewrites the 'z' command to 'cd'
eval "$(zoxide init --cmd cd zsh)"
alias zoxlist="zoxide query -l -s"
alias zlist="zoxide query -l -s"

# Hide homebrew env hint
HOMEBREW_NO_ENV_HINTS="true"

# Surpress npm warnings because im sick of seeing them
export npm_config_loglevel=silent

# Change default manual pager from less to nvim
export MANPAGER='nvim +Man!'

# Allows for proper config location (~/.config) of some terminal applications (ex aerc)
export XDG_CONFIG_HOME="$HOME/.config"

# . "$HOME/.local/bin/env"
export PATH=$PATH:$HOME/go/bin

# Set nvim as the default editor
export EDITOR='nvim'

# Stop git from opening nvim every time I pull
export GIT_MERGE_AUTOEDIT=no

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/jordan/.lmstudio/bin"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"

if command -v symfony &>/dev/null; then
  eval "$(symfony completion)"
fi

# Fix 'xterm-kitty' unknown terminal type in ssh
alias ssh='TERM=xterm-256color ssh'

# Alias function for harlequin to launch in mysql (accepts database name as arguement)
harlesql() {
  harlequin -a mysql -h localhost -p 3306 -U root --password "" --database "$1"
}


# Herd injected PHP 8.4 configuration.
export HERD_PHP_84_INI_SCAN_DIR="/Users/jordan/Library/Application Support/Herd/config/php/84/"


# Herd injected PHP binary.
export PATH="/Users/jordan/Library/Application Support/Herd/bin/":$PATH
